server:
  port: 8080
#Spring actuator指标监控
#配置需要开放的指标信息
#startup是BufferingApplicationStartup提供的指标
management:
    endpoints:
        web:
            exposure:
                include: health,info,startup
spring:
    application:
      name: demo
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        initial-size: 5
#        max-idle: 10
#        max-wait: 10000
#        min-idle: 5
#        password: 123
#        url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&autoReconnect=true
#        username: root
    main:
        allow-circular-references: true #允许循环依赖
test:
    bean:
        value:
            injection: PROPERTY-INJECTION
